AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR Repository for sample_github_actions_ecs_rollback"

Parameters:
  ProjectName:
    Type: String
  ProjectNameSnakeCase:
    Type: String
  RepositoryName:
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectNameSnakeCase}/${RepositoryName}"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keeps only 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }


Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub "${ProjectName}-ECRRepositoryUri"
