name: Deployment workflow

on:
  push:
    tags:
      - 'v*'

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: sample_ga_ecs_rollback/app_image

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set ENV (image tag)
        run: |
          echo "IMAGE_TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Configure AWS credentials by OpenID Connect
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.MY_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set ENV (check if the image tag already exists in ECR)
        run: |
          TAG_IN_ECR=$(aws ecr list-images --repository-name $ECR_REPOSITORY --query "imageIds[?imageTag=='${IMAGE_TAG}'].imageTag" --output text)
          if [ "$TAG_IN_ECR" = '' ]; then
            echo "EXISTS_IN_ECR=false" >> $GITHUB_ENV
          fi

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        if: ${{ env.EXISTS_IN_ECR == 'false' }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG code
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy ECS task & Log Group by CloudFormation
        env:
          MY_EXECUTION_ROLE_ARN: ${{ secrets.MY_EXECUTION_ROLE_ARN }}
          MY_TASK_ROLE_ARN: ${{ secrets.MY_TASK_ROLE_ARN }}
        run: |
          ./infra/sh/02-task.sh $IMAGE_TAG

